name: Build and Push to GHCR

on:
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get lowercase repository name
      run: |
        IMAGE_ID="${{ github.repository }}"

        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo "IMAGE_ID=${IMAGE_ID}" >>${GITHUB_ENV}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:app"
        push: true
        tags: |
          ghcr.io/${{ env.IMAGE_ID }}:latest
          ghcr.io/${{ env.IMAGE_ID }}:${{ github.event.release.tag_name }}

